app_home:
    path: /
    controller: App\Controller\HomeController::showhome

app_profile:
  path: /profile
  controller: App\Controller\User\UserController::showprofile

app_login:
  path: /login
  controller: App\Controller\SecurityController::login